name: Build

on:
  push:
    paths-ignore:
      - 'deploy/charts/**'
    branches: [ "main" ]

# Cancel in-progress runs of the same workflow on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build
  cancel-in-progress: true

permissions:
  contents: read

env:
  # Change this to your binary name
  APP_NAME: czertainly-hashicorp-vault-connector
  # Common build flags
  GOFLAGS: -trimpath
  LDFLAGS: -s -w -X "main.version=${{ github.sha }}"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux   # x86_64
            goarch: amd64
            ext: ""

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.26'
          cache: 'true'

      - name: Print Go env
        run: |
          go env
          go version
          go tool dist list | grep -E '^(linux|darwin|windows)/(amd64|arm64)$' || true

      - name: Build (${{ matrix.goos }}/${{ matrix.goarch }})
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: '0'
        run: |
          set -euo pipefail
          mkdir -p dist
          NAME="${APP_NAME}-${GOOS}-${GOARCH}"
          BIN="dist/${NAME}${{ matrix.ext }}"
          echo "Building -> ${BIN}"
          go build $GOFLAGS -ldflags "$LDFLAGS" -o "$BIN" ./cmd
          # Ensure executable bit on unix-like targets (Windows ignores it)
          chmod +x "$BIN" || true
          ls -lh "$BIN"

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
